### ISSUE TITLE
cspvarica does not support relative (percent) reducedim

### ISSUE THREAD

**Issue by cle1109** [scot-dev/scot#148]
I noticed that in contrast to `mvarica` (which uses PCA), `cspvarica` does not support a relative number for `reducedim` (e.g. 0.99 to retain 99% of the variance). This is a problem because the `Workspace` sets the default value of `reducedim` to 0.99.

What do you suggest to do @mbillingr? I guess it is not possible to run `cspvarica` with a relative number for `reducedim?`

**Comment by mbillingr** [comment]
Hmm.. that's a problem.

I'm not sure what's the best way to resolve this. The `reducedim` parameter works very differently for MVARICA and CSPVARICA. While CSPVARICA only accepts the number of componentes, MVARICA takes either the number of components, or a fractional variance, or `"no pca"` if you want to skip PCA altogether.

A relative reducedim does not make sense for CSP because we do not remove components based on their variance, but an absolute reducedim is not a practical default for PCA.

**Comment by cle1109** [comment]
A practical solution would be to set `reducedim` to `None.`

**Comment by mbillingr** [comment]
I'm not sure how practical that is, because I think you'll always want to remove some components.

**Comment by cle1109** [comment]
Yes, but in the case of MVARICA, I tend to reduce to a fixed absolute number of components and not a percentage. In the case of CSPVARICA, same thing.

**Comment by mbillingr** [comment]
True. I've mainly set the percentage default because that way it is described in the MVARICA paper.

**Comment by cle1109** [comment]
So let's set it to `None` then at least in the `Workspace`? We can leave the percentage default in MVARICA (CSPVARICA already has `np.inf` as its default, which we should probably replace with `None` to be consistent).

**Comment by mbillingr** [comment]
Sounds reasonable.
