### ISSUE TITLE
Questions about 'example/statistics.py'

### ISSUE THREAD

**Issue by dongqunxi** [scot-dev/scot#196]
Dear @mbillingr and @cbrnr ,
I am very interest in the example script 'statistics.py', here I have one question about it:
 ``` do_mvarica(varfit='class')``` 
1. I saw the introduction:```varfit='class', ‘class’ fits a different model for each class```, that means we got two MVAR models, right? 
2. If so why and how we get one set of sources from two class models?

Thanks a lot!

**Comment by cbrnr** [comment]
The procedure works as follows. First, we fit one (`ensemble`) or several (`class`, `trial`) VAR models to the data (i.e. the principal components). We get one set of sources because we run ICA on the residuals - these are just the differences between the predictions and the actual data.

For example, if we fit one VAR model per class (`class`), then we split the data into trials belonging to class 0 and trials belonging to class 1, fit separate VAR models, and compute separate residuals. Then, we concatenate the residuals from these two disjoint sets and run ICA.

Here's some pseudo-code of the steps, assuming that the EEG data is contained in `x`:

    var = scot.backend["var"]()

    # PCA
    c, d, xpca = scot.backend["pca"](x)

    # fit one VAR model per class
    r = []  # residuals
    for i in np.unique(cl):
        xpca_subset = subset(xpca.squeeze(), y, np.flatnonzero(cl == i))
        a = var.fit(xpca_subset)
        r.append(xpca_subset - var.predict(xpca_subset).squeeze())

    # ICA on residuals
    mx, ux = scot.backend['ica'](np.concatenate(r, axis=1), random_state=1)

    # undo PCA
    mx = mx.dot(d)  # mixing matrix
    ux = c.dot(ux)  # unmixing matrix

**Comment by dongqunxi** [comment]
Thanks @cbrnr ! Nice explanation, I understand better now!
