### ISSUE TITLE
Surrogates threshold making

### ISSUE THREAD

**Issue by dongqunxi** [scot-dev/scot#58]
Hi @kazemakase,
During causality analysis, if I want to make a significant threshold from the surrogates causality, how to do? You have shown the percentile strategy, is there any better strategy? Thanks!

**Comment by kazemakase** [comment]
Hi @dongqunxi 
I am not aware of a better method than comparing against the percentiles of surrogates. There may be better methods, but I never bothered to find out.

I particularly like the surrogate/percentile approach because of its simplicity and direct relation to hypothesis testing

- You have the null-hypothesis of *no connectivity*
- The surrogate approach destroys connectivity information in the data, but does not touch the signal spectra. Thus, the surrogate data is what the original data would look like if the null hypothesis was true.
- By drawing many surrogates you can estimate the distribution of  connectivity under the null hypothesis.
- You can get a p-value by comparing the original data against this distribution, or conversely, you can define a critical value at a percentile of your choice (e.g. 95%, 99%, etc).

**Comment by dongqunxi** [comment]
Hi @kazemakase , 
Thanks for your tips! This is indeed the convenient way to get the threshold.
