### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by mbillingr** [scot-dev/scot#69]
Currently we have a scot/config.py which does not do much. We should use it to set (at least) the following options:

 - default backend
 - default example storage location

Furthermore, we should try to parse user/distribution specific configurations. Can we do it like this?

  1. try to load ~/.scot_config.py (or maybe ~/.scot/config.py)
  2. if that fails try /etc/scot_config.py (what's the windows equivalent?)
  3. if that faill too use scot/config.py

I'm not sure if it's possible to import python scripts from arbitrary locations. Otherwise we could use Json configuration.

**Comment by cle1109** [comment]
Good idea. Why don't we just use a simple `config.ini`? There is a [configparser](https://docs.python.org/3/library/configparser.html) module which should handle this (although this might not work in Python 2 because it has been renamed - we would have to check that).

**Comment by kazemakase** [comment]
We could use that. Should be easy to wrap for both Python versions:

    try:
        from configparser import ConfigParser
    except ImportError:
        from ConfigParser import ConfigParser

But I'm rather fond of the idea to use Python as the configuration language for Python :)
If it is possible, and unless there are security concerns, I'd vote for a configuration or startup script.

**Comment by cle1109** [comment]
You're right, I didn't see that only the module name changed.

As much as I want to agree, I think a simple .ini file would be more than sufficient for our purposes and it is really a user-readable format. But this means we add in one more dependency (configparser, which is not that bad because it's in the standard library), so I'd be OK with having .py config files. Either way is fine with me.

Let's skip your second location (/etc corresponds to the registry on Windows and we don't want to mess with that - there are modules that deal with this sort of stuff; for example, PyQt has a nice configuration system that handles everything cross-platform). So I suggest that we

1. try to load ~/.scot_config.py
2. if the above fails, use the default configuration in scot/config.py.

**Comment by kazemakase** [comment]
(I don't consider things from the standard library a dependency.)

Correct me if I'm wrong, but Python should be usereadable enough, especially if we only set a few variables. Also, I suppose that anyone who is willing to play with the configuration can be assumed to have some basic Python knowledge.

I'd like to use the .py config files if they can be loaded easily. Otherwise let's use the configparser.

At least on Linux I'd try to load the configuration from /etc. I imagine this could be a very useful features for distribution maintainers. For example, an Arch Linux package could include the example data and set the search path accordingly, without patching the source code.


By the way, It's probably best to parse the configs on top of each other. So users can override specific global settings without copying the whole configuration.

**Comment by cle1109** [comment]
Of course you're right, Python is more than readable - I'm not arguing against using it for our config file anymore :-).

Loading the settings from `config.py` is a matter of `import config`, right?

Using /etc is a very Linux-specific issue and should be addressed in a separate issue. For me, this is not important for deciding how to implement our config system right now.

+1 for the ability to partly override global config options.

**Comment by kazemakase** [comment]
> Loading the settings from config.py is a matter of import config, right?

The crux is how to import them. You either have to modify `sys.path`, which is messy, or manually load the module.
Manual loading is different in Python 2.7, Python 3.3 and Python 3.4+: http://stackoverflow.com/q/67631

**Comment by cle1109** [comment]
Right, I only thought of the global config and forgot about the user config. This is pretty ugly if you ask me - maybe configparser is the better option after all.

**Comment by kazemakase** [comment]
I'm inclined to agree :(

**Comment by cle1109** [comment]
I know it's not ideal, but let's start with configparser and we can always replace it with something else later on.

**Comment by kazemakase** [comment]
True. I suggest the following procedure:

- load package config (`scot/config.ini`, these are our defaults and must be present)
- load system config if available (`/etc/scot_config.ini`, here package maintainers can override our defaults, this is simply not present on windows or when the package was installed from pypi.)
- load user config if available (`~/.scot_config.ini`)

Each config file overrides the settings in the previously parsed files.

**Comment by cle1109** [comment]
Perfect, LGTM!

**Comment by kazemakase** [comment]
Amazing! The ConfigParser (at least on Py3) supports loading a list of config files with exactly the overloading behavior we need.

**Comment by cle1109** [comment]
So hopefully this makes you forget you wanted to have .py files in the first place :-). Awesome - can't wait for the PR!

**Comment by kazemakase** [comment]
Currently I'm running local tests. Expect PR soon.

**Comment by cle1109** [comment]
Solved by #70.
